# Generated by Django 3.0.4 on 2020-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateName', models.CharField(max_length=30)),
                ('PartyName', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('voterid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='voterid',
            fields=[
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('voterid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=8)),
                ('Phoneno', models.CharField(max_length=11)),
            ],
        ),
    ]
