# Generated by Django 3.0.4 on 2020-03-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200321_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='locationid',
            new_name='locationID',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='locationid',
            new_name='locationID',
        ),
    ]
