# Generated by Django 3.0.4 on 2020-03-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200321_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='nvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voterid',
            name='DOB',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_date',
            field=models.DateField(default=None),
        ),
    ]
