# Generated by Django 3.0.4 on 2020-03-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200321_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'verbose_name_plural': 'election'},
        ),
    ]
